### ISSUE TITLE
Mana level and related

### ISSUE THREAD

**Issue by Zuljita** [Syndaryl/DFRPGRandomDungeonGenerator#16]
We need to generate this

**Comment by Syndaryl** [comment]
I suggest we handle this much like lighting level: Have an overall dungeon level, and then a chance of a modification in individual dungeon rooms.

Off the top of my head, I suggest 80% normal mana on a dungeon level, and 80-90% consistent with dungeon level on a room-by-room basis.

**Comment by Syndaryl** [comment]
Done.
