### ISSUE TITLE
Maps are not scaled correctly

### ISSUE THREAD

**Issue by Zuljita** [Syndaryl/DFRPGRandomDungeonGenerator#29]
Hexes are 10 feet

**Comment by Syndaryl** [comment]
On further investigation, they may be 5 feet. Still not 1 yard, however.

**Comment by nasfarley88** [comment]
On further investigation, it's still not quite right, but this image should reveal the scaling we need  ![selection_164](https://user-images.githubusercontent.com/1312119/32779455-c1b6b7ec-c935-11e7-95b4-2a56cf7d9de7.png)

**Comment by Syndaryl** [comment]
Thanks @nasfarley88, that's very helpful. I'll take a look at this tonight.

**Comment by nasfarley88** [comment]
@Syndaryl I'm having a look now but I'm struggling to figure out where hex size is determined. Any pointers (e.g. functions to look in)?

**Comment by nasfarley88** [comment]
Pull request #34  should fix this now, but please feel free to test.

**Comment by Syndaryl** [comment]
This is sorted now, although I am looking at the issue of scaling again.
