### ISSUE TITLE
No dungeon appearing after latest commit

### ISSUE THREAD

**Issue by awesomeamyg** [Syndaryl/DFRPGRandomDungeonGenerator#73]
It looks like something went wrong with this commit https://github.com/Syndaryl/DFRPGRandomDungeonGenerator/commit/cbf73113d3f8807d50a80bb3383f41d6d2cde2ac while trying to clean up the code. 

I downloaded the latest version and no dungeon would appear on my screen.

I tried downloading the repo at the commit before that, https://github.com/Syndaryl/DFRPGRandomDungeonGenerator/commit/809cc9768c85f1dd6e676ec6733acdefca7f7e1f, and it seemed to be working properly

**Comment by Syndaryl** [comment]
I've rolled back the last commit - apparently that's a particularly stubborn stain.
